# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Isorna.net
tagline:          '&lt;&nbsp;My life in brackets /&gt;'
description:      'Made by <a href="https://twitter.com/isorna" target="_blank">@isorna</a>, thanks to <a href="http://getpoole.com" target="_blank">Poole</a>.'
url:              http://isorna.github.io
baseurl:          /

author:
  name:           'Alvaro Isorna'
  url:            https://twitter.com/isorna

paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/isorna/isorna.github.io

# Extra
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
